---
title: "Portfolio 1"
---

> This piece of the portfolio includes data cleaning, model tests for my first year project.
The data for the mother and teen project was cleaned to use for analysis and visualization. The model was built, and the model fits.

```{r load-packages, message=FALSE}
library(tidyverse) 
library(tidyr)
```

```{r}
library(tidyverse)
library(dplyr)
library(haven)
Mother_and_teen_data <- read_sav("Mother_and_teen_data.sav")
#View(Mother_and_teen_data)
Mother_and_teen_data$Race3 <- as.factor(Mother_and_teen_data$Race3)
select(Mother_and_teen_data, PSE, CD_1, CD_2, CD_3, PAPWARM, PAPmoni, PAPsolic, PAPrule, Race3)
ggplot(Mother_and_teen_data, aes(x=PSE, y=CD_1, fill = Race3)) +  geom_smooth(size=1, alpha=0.4) +
 geom_point(aes(color=Race3))+
  labs(title="PSE and adolescents' disobeying parents", x="Parental self-efficacy", y="Disobeying parents among adolescents" ) 
  
```

```{r}
ggplot(Mother_and_teen_data, aes(x=PSE, y=CD_2, fill = Race3)) +  geom_smooth(size=1, alpha=0.4) +
 geom_point(aes(color=Race3))+
  labs(title="PSE and adolescents' school misconduct", x="Parental self-efficacy", y="school misconduct among adolescents" ) 
  
```

```{r}
ggplot(Mother_and_teen_data, aes(x=PSE, y=CD_3, fill = Race3)) +  geom_smooth(size=1, alpha=0.4) +
 geom_point(aes(color=Race3))+
  labs(title="PSE and adolescents' substance use", x="Parental self-efficacy", y="substance use among adolescents" ) 
```
Trying to combine three type of adolescent deviance
```{r}
Mother_and_teen_data$Race3 <- as.factor(Mother_and_teen_data$Race3) 
Mother_and_teen_data <- Mother_and_teen_data %>%
mutate(ad_deviance=CD_1 + CD_2 + CD_3)
ggplot(Mother_and_teen_data, aes(x=PSE, y=ad_deviance)) +  geom_smooth(size=1, alpha=0.4) +
 geom_point(aes(color=Race3)) +
  labs(title="PSE and adolescents' substance use", x="Parental self-efficacy", y="adolescent deviance" ) 
```
SEM to test the model and its fits
```{r} 
model1<-"AdolD=~CD_1 +CD_2 +CD_3
EffectP=~PAPmoni+PAPWARM+PAPsolic+PAPrule
PSE~EffectP
AdolD~EffectP + PSE"
#residual correlations
PAPmoni~~PAPsoli
PAPmoni~~PAPrule
PAPWARM~~PAPsoli
CD_1~~CD_2
CD_1~~CD_3
CD_2~~CD_3
```
the model fits.
```{r} 
library(lavaan)
library(readxl)
library(dplyr)
library(haven)
teendata<- Mother_and_teen_data %>% filter( !is.na(PerPW)) 
fit1<- sem(model1, data=Mother_and_teen_data)
fit1
summary(fit1, standardized=TRUE, ci=TRUE, fit.measures=TRUE)
modindices(fit1, sort.=TRUE)
inspect(fit1, what="std")
```