---
title: "Portfolio 6"
---

```{r data}
library(tidyverse)
library(dplyr)
library(haven)
teen_survey<- read_sav("teen_survey.sav")
tss<- read_sav("tss.sav")
```
```{r pc}
library(lme4)
library(merTools)
library(semPlot)
library(lavaan)
library(readxl)
library(dplyr)
library(haven)
```


```{r multilevel ex}
model1<-lmer(ex~1+(1|exter),REML = FALSE, data=tss)
summary(model1)
confint(model1)

ICC(outcome = "ex", group="exter",data=tss)
```


```{r multilevel2 ex}
#add level 1 predictor
model2<-lmer(ex~1+Gender+(1|exter), REML= FALSE, data= tss)
summary(model2)
anova(model1, model2)
confint(model2)
```
```{r multilevel3 ex}
model3<-lmer(ex~1+Gender+(1|exter)+country, REML= FALSE, data= tss)
summary(model3)
anova(model2, model3)
confint(model3)
#does not think it make any sense statistically.
```
```{r model}
model<-"Parents_expectations=~exter +inter+Rpro
Adolescents_behaviors=~int+ex+Rpr
Parents_expectations~Adolescents_behaviors"
#residual correlations
exter~~inter
inter~~Rpro
exter~~Rpro

int~~ex
Rpr~~ex
Rpr~~int




library(lavaan)
library(readxl)
library(dplyr)
library(haven)

fit<- sem(model, data=teen_survey)

summary(fit, standardized=TRUE, ci=TRUE, fit.measures=TRUE)
modindices(fit, sort.=TRUE)
inspect(fit, what="std")
fitmeasures(fit)


parameterestimates(fit, standardized = TRUE)
fitted(fit)
residuals(fit)
fitmeasures(fit)
modificationindices(fit, sort. = TRUE)
semPaths(fit, what="paths", whatLables="par", rotation=2)

fitmeasures(fit)

#not a good fit.
```
```{r model retry}
model2<-"Parents_expectations=~exter +inter+ pros+ stem
Adolescents_behaviors=~int+ex+pr+st
Parents_expectations~Adolescents_behaviors"
#residual correlations
exter~~inter
pros~~stem

int~~ex
pr~~int
pr~~ex
st~~pr
st~~ex
st~~int




library(lavaan)
library(readxl)
library(dplyr)
library(haven)

fit2<- sem(model2, data=teen_survey)

summary(fit2, standardized=TRUE, ci=TRUE, fit.measures=TRUE)
modindices(fit2, sort.=TRUE)
inspect(fit2, what="std")
fitmeasures(fit2)


parameterestimates(fit2, standardized = TRUE)
fitted(fit2)
residuals(fit2)
fitmeasures(fit2)
modificationindices(fit2, sort. = TRUE)
semPaths(fit2, what="paths", whatLables="par", rotation=2)

fitmeasures(fit2)

#poor fit.
```


